### PR TITLE
feat(module add): add module peer-dependencies args

### LINKED ISSUE #385: install module peer-dependencies
when installing modules it can be common for them to have another dependency that needs to be installed. rather than requiring this to be installed separately, it would be nice for modules in nuxt/modules to specify any additional packages that have to be installed

### PR DESCRIPTION
**Pull request by shinGangan**
### 🔗 Linked issue

closed #385 

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

I created an args for the `nuxi module add` command to install dependent libraries together.

The two added args are:

#### `--install`: Install peer dependencies.

```sh
# installiing @nuxt/eslint module and installing eslint
npx nuxi module add eslint --install eslint
```

If you specify only the xyz argument, install peerDependencies defined in the module to be installed.

```sh
# installiing @nuxt/eslint module and installing peerDependencies in pacakge.json
npx nuxi module add eslint --install
```

You can install multiple peer dependencies by specifying multiple peer dependencies.

```sh
# installing @nuxt/eslint module and installing eslint, prettier
npx nuxi module add eslint --install eslint --install prettier
```

If not specified, only the module will be installed as before.

```sh
# installing only @nuxt/eslint module
npx nuxi module add eslint
```

#### `--install-dev`:  Install peer dependencies for devDependenies

There are some cases where it is preferable to use `devDependencies` instead of `dependencies` to install peer dependencies.  In that case, specify this option as well and install it to devDependencies.

```sh
# installiing @nuxt/eslint module and installing eslint in devDependencies
npx nuxi module add eslint --install-dev eslint
```

You can also install multiple peer dependencies by specifying multiple peer dependencies.

```sh
# installiing @nuxt/eslint module and installing eslint, prettier in devDependencies
npx nuxi module add eslint --install-dev eslint --install-dev prettier
```

#### The following is displayed in the help

```sh
USAGE module add [OPTIONS] <MODULENAME>

ARGUMENTS

  MODULENAME    Module name    

OPTIONS

                       --cwd    Current working directory                              
                  --logLevel    Log level                                              
               --skipInstall    Skip npm install                                       
                --skipConfig    Skip nuxt.config.ts update                             
                   --install    Installing module peer dependencies.                   
  -installDev, --install-dev    Installing module peer dependencies in devDependencies.                  
```

### 🚀 Examples

```sh
# installing only @nuxt/eslint module
npx nuxi module add eslint

# installiing @nuxt/eslint module and installing eslint
npx nuxi module add eslint --install eslint

# installing @nuxt/eslint module and installing eslint, prettier
npx nuxi module add eslint --install eslint --install prettier

# installing @nuxt/eslint module and installing eslint, prettier in devDependencies 
npx nuxi module add eslint --install-dev eslint --install-dev prettier

# installing @nuxt/test-utils module and installing related libraries in devDependencies 
 npx nuxi module add test-utils --install-dev vitest --install-dev @vue/test-utils --install-dev happy-dom --install-dev playwright-core

# installing nuxt-graphql-server module and installing related libraries 
 npx nuxi module add nuxt-graphql-server --install graphql --install @apollo/server --install @as-integrations/h3
```

#### old proposal ~~Additional expansion proposals~~

Depending on the module, there are cases where the creator sets peerDependencies.

By adding the following items to the nuxt module, there is no need for the user to specify `peerDeps`.

```diff
  name: test-utils
  description: Test utilities for Nuxt
  repo: nuxt/test-utils#main
  npm: '@nuxt/test-utils'
+ peer: 
+   - vitest
+   - @vue/test-utils
+   - happy-dom
+   - playwright-core
  icon: nuxt.svg
  github: https://github.com/nuxt/test-utils
  website: https://nuxt.com/docs/getting-started/testing
  learn_more: ''
  category: Devtools
  type: official
  maintainers:
    - name: Daniel Roe
      github: danielroe
      twitter: danielcroe
    - name: Anthony Fu
      github: antfu
      twitter: antfu7
  compatibility:
    nuxt: ^3.0.0
    requires: {}
```

#### docs

I am also preparing the documentation.

- [exp branch](https://github.com/shinGangan/nuxt/commits/exp/add-peer-deps-in-docs/)

### CODE REVIEW

**Comment by shinGangan** [comment]
Hi @danielroe 👋

The features in the issue( #385 ) were ones I really wanted as well.
So I implemented it.

I would be happy if you could leave a comment and review when you have time. 💚

**Comment by danielroe** [comment]
Thank you for looking at this! ❤️ 

@pi0 had the idea of doing this automatically in [`nypm`](https://github.com/unjs/nypm). That would mean we wouldn't need to update `nuxt/modules`, but would just respect whatever user defines in `package.json`. 

What do you think?

**Comment by pi0** [comment]
Thanks for PR dear @shinGangan 

Yeah as @danielroe mentioned probably automatically installing peer deps makes best sense. As i know npm and pnpm already do it automatically for peer dependencies.

Still it might be convenient (and also faster to deliver and more covering) to support an option to the same `nuxt module add` to install additional dependencies, however i think we can simplify it to a flag like `--install [...packages]` / `--install-dev [...packages]` (also make it clear it is an additional config)

**Comment by shinGangan** [comment]
`--install [...packages]` / `--install-dev [...packages]` is easier to understand than the current implementation. thank you.

---

current(before) -> comment(after)

`--peerDeps, -p` -> `--install, -i`
`--devDeps, -D` -> `--install-dev, -iD`

**Comment by pi0** [comment]
(i think we could only keep long args if you are happy to. mainly to keep it readable + keep `-i` for possible future uses reserved)

**Comment by shinGangan** [comment]
> (i think we could only keep long args if you are happy to. mainly to keep it readable + keep `-i` for possible future uses reserved)

I agree with this ⭕️.
Providing -i may cause confusion for users (Does -i install modules? Or only peer dependencies? etc.)

**Comment by shinGangan** [comment]
Dear @pi0 , @danielroe .

Fixed to install peerDependency. Does it match your expectations?

**Pull request closed without merging**
